# docker-compose.prod.yml
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: jurelex-backend
    restart: always
    environment:
      - MILVUS_HOST=host.docker.internal
      - MILVUS_PORT=19530
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "5050:5050"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: jurelex-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
